import time
import uuid
import json
from datetime import datetime
from athena_system.config import MOCK_MODE

class MemoryManager:
    def __init__(self):
        self.collection = None
        if not MOCK_MODE:
            import chromadb
            client = chromadb.Client()
            self.collection = client.create_collection("athena_memory")
        else:
            self.mock_store = []

    def add_memory(self, content, agent_id, tags=None):
        """
        Adds a memory with Provenance tracking.
        """
        memory_id = str(uuid.uuid4())
        timestamp = datetime.now().isoformat()
        
        metadata = {
            "agent_id": agent_id,
            "timestamp": timestamp,
            "provenance": f"Generated by {agent_id} at {timestamp}",
            "tags": ",".join(tags) if tags else ""
        }
        
        print(f"💾 Memory Manager: Storing memory from {agent_id}...")
        
        if MOCK_MODE:
            self.mock_store.append({"id": memory_id, "content": content, "metadata": metadata})
        else:
            self.collection.add(
                documents=[content],
                metadatas=[metadata],
                ids=[memory_id]
            )
        return memory_id

    def retrieve_memory(self, query, limit=3):
        """
        Retrieves relevant memories.
        """
        print(f"🧠 Memory Manager: Recalling memories for '{query}'...")
        
        if MOCK_MODE:
            # Simple keyword match for mock mode
            results = [m for m in self.mock_store if query.lower() in m['content'].lower()]
            return results[:limit]
        else:
            results = self.collection.query(
                query_texts=[query],
                n_results=limit
            )
            return results

    def consolidate_memory(self):
        """
        Async background process to merge and curate memories.
        """
        print("🧹 Memory Manager: Running consolidation (Async)...")
        # In a real system, this would use an LLM to summarize recent memories
        # and delete duplicates.
        pass

if __name__ == "__main__":
    manager = MemoryManager()
    manager.add_memory("Client X is interested in AI Governance.", "hermes-agent", ["client", "governance"])
    memories = manager.retrieve_memory("Governance")
    print(json.dumps(memories, indent=2))
